
=head1 NAME

Hustle::Table - Fast dynamic dispatching to subroutines

=head1 SYNOPSIS

  use Hustle::Table;

  #1. Create a new object
  my $table=Hustle::Table->new;

  #2. Add entries which contain:
  #	matcher:	required. The matcher  (ie regex, string, number) to test with
  #	sub:		required. The sub to call when matcher is 'true' when testing input
  #	label:		optional. For identification
  #	count:		optional. Used as priority when adding (larger number=> higher priority)
  #Can either be a array ref or hash ref

  $table->add(
  	{match=>qr/regex match/, sub=>sub{ #dispatch vector}}, 	#entry as a hash ref
	[qr/another/,sub{},"my label",10],			#entry as array ref
	[undef,sub {},"default",undef]				#undef matcher is default match all
  );

  #3. Prepare a dispatcher:
  # 	A dispatcher is sub reference, which is called directly with in put to match
  #     Different types, caching and other processing options.

  my $dispatch=$table->prepare_dispatcher(type=>"online", cache=>{}, reorder=>1); # or loop, loop_cached, dynamic_cached


  #4. Dispatch from input
  $dispatch->("thing to match","optional", "arguemnts");	# any number of arguments passsed to sub


  #Training is also possible please see below
  

=head1 DESCRIPTION

This module provides small class to construct a dispatch table and build a dispatcher subroutine for it. Multiple dispatchers types to choose from give the user tunable behaviour.


 
=over 

=item Uses buildin perl features  (regex, smartmatch)

=item Cached prematching (optional)

=item Basic hit count and optimising (optional)

=item Fall through/catch all matching

=back

=head2 EXPORT

No exports. Please use the object interface.



=head2 How it works

The table is essentially a list of at least one entry. Any consists of:

=over

=item match

	regular expression, string, number

=item sub

	target subroutine to call when the regex matches

=item label

	label to help the user track this entry

=item count

	running total on how many times an entry has been dispatched successfully
	or also a prioity level

=back



=head2 Adding Entries

More entrys are added by the user, in either hash ref or array ref format, using the C<add> method.
Array entries must contain four elements, in the order of:
	
	[$matcher,$sub,$label,$count]
	{matcher=>$matcher, sub=>$sub, label=>$label, count=>$count}

C<$sub> is the only item that must be defined and must be a CODE reference

C<$matcher> can be anything that smartmatching can handle. However the focus on this module is on strings
and regular expressions

	"match exaclty this stirng"
	qr|match and capture (this|that)|

When C<$matcher> is a regex, any capturing is accessable in the target sub.

C<$label> is a user defined item to allows identification of the entry. This is useful for saving/loading from configuration files etc.

C<$count> This is a dual purpose attributes. When adding entries to the list, it is used as a priority. Higher numeric values are a higher priority. The list is sorted in decenting order of priority, meaning the highest priority is the first element in the list.

During running of the dispatch, this is a tally recording how many times,the entry has been matched. This information can be then used to as a priority later and the list reorded.




The last element in the list (which is always present) is the default/ or catch all  matcher.

The list always has one entry which is the fallback or default which is called when no other entries match.


Once the a table is created entries are added as an even numbered list of matcher=> sub pairs.

	my $table=Hustle::Table->new;

	$table->add(qr/Hello/, sub { say "There"; return;});





=head1 Performance

The concept is to perform less searching to find the dispatch vector. However the type of input does play an important role in determining the best way perform the search.

=over

=item Uniformly distributed input


For uniformly distributed input, the fastest method is to use the dynamically generated non caching 
method. Resorting or optimising search order has no real effect as the probablilty of each case is equal. In this case the method with the least run time overhead will perform the best.

Caching can have a detrimental effect as it take cpu time to consult the cache

=item 




=head1 SEE ALSO

Mention other useful documentation such as the documentation of
related modules or operating system documentation (such as man pages
in UNIX), or any relevant external documentation such as RFCs or
standards.

If you have a mailing list set up for your module, mention it here.

If you have a web site set up for your module, mention it here.

=head1 AUTHOR

Ruben Westerberg, E<lt>drclaw@sd.apple.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2021 by Ruben Westerberg

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.28.2 or,
at your option, any later version of Perl 5 you may have available.


=cut
