<<<<<<< HEAD
name: Perl
=======
name: CI
>>>>>>> 64ed8f35e34ddce6437f5309cbf4e5241af68521

on:
  push:
  pull_request:
  workflow_dispatch:
<<<<<<< HEAD
  schedule:
    - cron: '42 5 * * *'
=======
>>>>>>> 64ed8f35e34ddce6437f5309cbf4e5241af68521

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
<<<<<<< HEAD
        perl: [ '5.36', '5.34','5.32','5.30', '5.28', '5.26' ]
=======
        perl: [ '5.30', '5.36' ]
>>>>>>> 64ed8f35e34ddce6437f5309cbf4e5241af68521
        exclude:
          - runner: windows-latest
            perl: '5.36'

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
=======
    - uses: actions/checkout@v2
>>>>>>> 64ed8f35e34ddce6437f5309cbf4e5241af68521

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ ( startsWith( matrix.runner, 'windows-' ) && 'strawberry' ) || 'default' }}

    - name: Show Perl Version
      run: |
        perl -v

    - name: Install Modules
      run: |
        cpanm -v
        cpanm --installdeps --notest .

<<<<<<< HEAD
=======
    - name: Run tests
      run: |
        perl Makefile.PL
        make
        make test

>>>>>>> 64ed8f35e34ddce6437f5309cbf4e5241af68521
    - name: Show Errors on Windows
      if:  ${{ failure() && startsWith( matrix.runner, 'windows-')}}
      run: |
         ls -l C:/Users/
         ls -l C:/Users/RUNNER~1/
         cat C:/Users/runneradmin/.cpanm/work/*/build.log

    - name: Show Errors on Ubuntu
      if:  ${{ failure() && startsWith( matrix.runner, 'ubuntu-')}}
      run: |
         cat /home/runner/.cpanm/work/*/build.log

    - name: Show Errors on OSX
      if:  ${{ failure() && startsWith( matrix.runner, 'macos-')}}
      run: |
         cat  /Users/runner/.cpanm/work/*/build.log

<<<<<<< HEAD
    - name: Run tests
      env:
        AUTHOR_TESTING: 1
        RELEASE_TESTING: 1
      run: |
        perl Makefile.PL
        make
        make test


=======
>>>>>>> 64ed8f35e34ddce6437f5309cbf4e5241af68521
